/** @type {import('next').NextConfig} */
const nextConfig = {
	images: {
		unoptimized: true,

		// remotePatterns: [
		// 	{
		// 		protocol: "https",
		// 		hostname: "res.cloudinary.com",
		// 		port: "",
		// 		pathname: "**",
		// 	},
		// 	{
		// 		protocol: "https",
		// 		hostname: "abs.twimg.com",
		// 		port: "",
		// 		pathname: "**",
		// 	},
		// 	{
		// 		protocol: "https",
		// 		hostname: "pbs.twimg.com",
		// 		port: "",
		// 		pathname: "**",
		// 	},
		// 	{
		// 		protocol: "https",
		// 		hostname: "yt3.ggpht.com",
		// 		port: "",
		// 		pathname: "**",
		// 	},
		// 	{
		// 		protocol: "https",
		// 		hostname: "i.ytimg.com",
		// 		port: "",
		// 		pathname: "**",
		// 	},
		// 	{
		// 		protocol: "https",
		// 		hostname: "api.producthunt.com",
		// 		port: "",
		// 		pathname: "**",
		// 	},
		// 	{
		// 		protocol: "https",
		// 		hostname: "avatars.githubusercontent.com",
		// 		port: "",
		// 		pathname: "**",
		// 	},
		// 	{
		// 		protocol: "https",
		// 		hostname: "d3t3ozftmdmh3i.cloudfront.net",
		// 		port: "",
		// 		pathname: "**",
		// 	},
		// 	{
		// 		protocol: "https",
		// 		hostname: "i1.sndcdn.com",
		// 		port: "",
		// 		pathname: "**",
		// 	},
		// 	{
		// 		protocol: "https",
		// 		hostname: "media.rss.com",
		// 		port: "",
		// 		pathname: "**",
		// 	},
		// 	{
		// 		protocol: "https",
		// 		hostname: "feeds.podcastmirror.com",
		// 		port: "",
		// 		pathname: "**",
		// 	},
		// 	{
		// 		protocol: "https",
		// 		hostname: "ssl-static.libsyn.com",
		// 		port: "",
		// 		pathname: "**",
		// 	},
		// 	{
		// 		protocol: "https",
		// 		hostname: "static.libsyn.com",
		// 		port: "",
		// 		pathname: "**",
		// 	},
		// 	{
		// 		protocol: "https",
		// 		hostname: "megaphone.imgix.net",
		// 		port: "",
		// 		pathname: "**",
		// 	},
		// 	{
		// 		protocol: "https",
		// 		hostname: "storage.pinecast.net",
		// 		port: "",
		// 		pathname: "**",
		// 	},
		// 	{
		// 		protocol: "https",
		// 		hostname: "storage.buzzsprout.com",
		// 		port: "",
		// 		pathname: "**",
		// 	},
		// 	{
		// 		protocol: "https",
		// 		hostname: "pbcdn1.podbean.com",
		// 		port: "",
		// 		pathname: "**",
		// 	},
		// 	{
		// 		protocol: "https",
		// 		hostname: "image.simplecastcdn.com",
		// 		port: "",
		// 		pathname: "**",
		// 	},
		// 	{
		// 		protocol: "https",
		// 		hostname: "media.redcircle.com",
		// 		port: "",
		// 		pathname: "**",
		// 	},
		// 	{
		// 		protocol: "https",
		// 		hostname: "assets.pippa.io",
		// 		port: "",
		// 		pathname: "**",
		// 	},
		// 	{
		// 		protocol: "https",
		// 		hostname: "www.omnycontent.com",
		// 		port: "",
		// 		pathname: "**",
		// 	},
		// 	{
		// 		protocol: "https",
		// 		hostname: "images.transistor.fm",
		// 		port: "",
		// 		pathname: "**",
		// 	},
		// 	{
		// 		protocol: "https",
		// 		hostname: "images.squarespace-cdn.com",
		// 		port: "",
		// 		pathname: "**",
		// 	},
		// 	{
		// 		protocol: "https",
		// 		hostname: "cloud259.com",
		// 		port: "",
		// 		pathname: "**",
		// 	},
		// 	{
		// 		protocol: "https",
		// 		hostname: "deow9bq0xqvbj.cloudfront.net",
		// 		port: "",
		// 		pathname: "**",
		// 	},
		// 	{
		// 		protocol: "https",
		// 		hostname: "d3wo5wojvuv7l.cloudfront.net",
		// 		port: "",
		// 		pathname: "**",
		// 	},
		// 	{
		// 		protocol: "https",
		// 		hostname: "episodes.castos.com",
		// 		port: "",
		// 		pathname: "**",
		// 	},
		// 	{
		// 		protocol: "https",
		// 		hostname: "s3.castbox.fm",
		// 		port: "",
		// 		pathname: "**",
		// 	},
		// 	{
		// 		protocol: "https",
		// 		hostname: "img.transistor.fm",
		// 		port: "",
		// 		pathname: "**",
		// 	},
		// 	{
		// 		protocol: "http",
		// 		hostname: "static-1.ivoox.com",
		// 		port: "",
		// 		pathname: "**",
		// 	},
		// 	{
		// 		protocol: "https",
		// 		hostname: "triathlon.podcaster.de",
		// 		port: "",
		// 		pathname: "**",
		// 	},
		// 	{
		// 		protocol: "https",
		// 		hostname: "image.ausha.co",
		// 		port: "",
		// 		pathname: "**",
		// 	},
		// 	{
		// 		protocol: "https",
		// 		hostname: "sdmedia.playser.cadenaser.com",
		// 		port: "",
		// 		pathname: "**",
		// 	},
		// 	{
		// 		protocol: "https",
		// 		hostname: "laufendentdecken-podcast.at",
		// 		port: "",
		// 		pathname: "**",
		// 	},
		// 	{
		// 		protocol: "https",
		// 		hostname: "images.podigee-cdn.net",
		// 		port: "",
		// 		pathname: "**",
		// 	},
		// 	{
		// 		protocol: "http",
		// 		hostname: "irun.ca",
		// 		port: "",
		// 		pathname: "**",
		// 	},
		// 	{
		// 		protocol: "https",
		// 		hostname: "www.trailrunnersdog.de",
		// 		port: "",
		// 		pathname: "**",
		// 	},
		// 	{
		// 		protocol: "https",
		// 		hostname: "artwork.captivate.fm",
		// 		port: "",
		// 		pathname: "**",
		// 	},
		// 	{
		// 		protocol: "https",
		// 		hostname: "media.zencastr.com",
		// 		port: "",
		// 		pathname: "**",
		// 	},
		// 	{
		// 		protocol: "https",
		// 		hostname: "assets.blubrry.com",
		// 		port: "",
		// 		pathname: "**",
		// 	},
		// 	{
		// 		protocol: "http",
		// 		hostname: "www.running-podcast.de",
		// 		port: "",
		// 		pathname: "**",
		// 	},
		// 	{
		// 		protocol: "https",
		// 		hostname: "kajabi-storefronts-production.kajabi-cdn.com",
		// 		port: "",
		// 		pathname: "**",
		// 	},
		// 	{
		// 		protocol: "https",
		// 		hostname: "assets.fireside.fm",
		// 		port: "",
		// 		pathname: "**",
		// 	},
		// 	{
		// 		protocol: "https",
		// 		hostname: "medias.podcastics.com",
		// 		port: "",
		// 		pathname: "**",
		// 	},
		// 	{
		// 		protocol: "https",
		// 		hostname: "1bmnl3g.podcaster.de",
		// 		port: "",
		// 		pathname: "**",
		// 	},
		// 	{
		// 		protocol: "https",
		// 		hostname: "static.iono.fm",
		// 		port: "",
		// 		pathname: "**",
		// 	},
		// 	{
		// 		protocol: "https",
		// 		hostname: "audioboom.com",
		// 		port: "",
		// 		pathname: "**",
		// 	},
		// 	{
		// 		protocol: "https",
		// 		hostname: "i0.wp.com",
		// 		port: "",
		// 		pathname: "**",
		// 	},
		// 	{
		// 		protocol: "http",
		// 		hostname: "www.podcast.de",
		// 		port: "",
		// 		pathname: "**",
		// 	},
		// 	{
		// 		protocol: "http",
		// 		hostname: "swimbikerun.pl",
		// 		port: "",
		// 		pathname: "**",
		// 	},
		// 	{
		// 		protocol: "https",
		// 		hostname: "is1-ssl.mzstatic.com",
		// 		port: "",
		// 		pathname: "**",
		// 	},
		// ],
	},
	experimental: {
		serverActions: {
			allowedOrigins: ["therunclub.xyz"],
			bodySizeLimit: "3mb",
		},
	},
};

export default nextConfig;
